# Generated by Django 6.1.1 on 2026-09-30 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('business_type', models.CharField(max_length=100, verbose_name='Business Type')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner Email')),
                ('notification_preferences', models.JSONField(default=dict, help_text='JSON object with notification preferences', verbose_name='Notification Preferences')),
                ('urgent_keywords', models.TextField(default='emergency,urgent,immediately,critical,accident,cannot wait', help_text='Comma-separated list of urgent keywords', verbose_name='Urgent Keywords')),
                ('escalation_rules', models.JSONField(default=dict, help_text='JSON object with escalation rules', verbose_name='Escalation Rules')),
                ('auto_escalate_on_emergency', models.BooleanField(default=True, verbose_name='Auto Escalate on Emergency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_config', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Escalation Config',
                'verbose_name_plural': 'Escalation Configs',
            },
        ),
        migrations.CreateModel(
            name='ReceptionistConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Callie', max_length=100, verbose_name='Receptionist Name')),
                ('personality', models.TextField(default='Friendly, professional and concise.', verbose_name='Personality')),
                ('greeting', models.TextField(default='Hello! Thank you for calling. My name is {name}, your virtual receptionist. How can I help you today?', verbose_name='Greeting')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('professional', 'Professional')], default='professional', max_length=50, verbose_name='Tone')),
                ('business_description', models.TextField(blank=True, verbose_name='Business Description')),
                ('main_responsibilities', models.TextField(blank=True, help_text='List the main responsibilities of the AI receptionist', verbose_name='Main Responsibilities')),
                ('max_conversation_length', models.IntegerField(default=10, help_text='Maximum number of turns in a conversation', verbose_name='Max Conversation Length')),
                ('escalation_threshold', models.IntegerField(default=3, help_text='Number of failed attempts before escalating', verbose_name='Escalation Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_config', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Receptionist Config',
                'verbose_name_plural': 'Receptionist Configs',
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, verbose_name='Day')),
                ('is_open', models.BooleanField(default=True, verbose_name='Is Open')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['day'],
                'unique_together': {('business', 'day')},
            },
        ),
    ]
