# Generated by Django 6.1.1 on 2026-09-30 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Sender Name')),
                ('sender_number', models.CharField(blank=True, max_length=20, verbose_name='Sender Number')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='Sender Email')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('website', 'Website Chat'), ('email', 'Email')], max_length=20, verbose_name='Channel')),
                ('content', models.TextField(verbose_name='Content')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI Response')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20, verbose_name='Urgency')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10, verbose_name='Direction')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='External ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='businesses.business')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='sms_message_busines_50bb57_idx'), models.Index(fields=['channel'], name='sms_message_channel_d1ee02_idx'), models.Index(fields=['status'], name='sms_message_status_0c4635_idx'), models.Index(fields=['urgency'], name='sms_message_urgency_9e6462_idx')],
            },
        ),
    ]
