# Generated by Django 6.1.1 on 2026-09-30 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('source', models.CharField(choices=[('call', 'Call'), ('message', 'Message'), ('website', 'Website'), ('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=50, verbose_name='Source')),
                ('last_interaction', models.DateTimeField(blank=True, null=True, verbose_name='Last Interaction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'name'], name='contacts_co_busines_edc5ae_idx'), models.Index(fields=['business', 'email'], name='contacts_co_busines_a61c83_idx'), models.Index(fields=['business', 'phone'], name='contacts_co_busines_a7e3d8_idx')],
            },
        ),
    ]
