# Generated by Django 6.1.1 on 2026-09-30 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True, verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('category', models.CharField(choices=[('general', 'General'), ('hours', 'Business Hours'), ('pricing', 'Pricing'), ('services', 'Services'), ('location', 'Location'), ('payment', 'Payment'), ('appointment', 'Appointment'), ('other', 'Other')], default='general', max_length=20, verbose_name='Category')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='businesses.business')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='knowledge_f_busines_360ab4_idx'), models.Index(fields=['category'], name='knowledge_f_categor_6f5794_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('category', models.CharField(choices=[('business_info', 'Business Information'), ('services', 'Services'), ('pricing', 'Pricing'), ('policies', 'Policies'), ('hours', 'Opening Hours'), ('contact', 'Contact Information'), ('locations', 'Locations'), ('special_instructions', 'Special Instructions'), ('other', 'Other')], max_length=30, verbose_name='Category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='knowledge_k_busines_fa420c_idx'), models.Index(fields=['category'], name='knowledge_k_categor_c8dbf6_idx')],
            },
        ),
    ]
