# Generated by Django 6.1.1 on 2026-09-30 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('caller_name', models.CharField(blank=True, max_length=255, verbose_name='Caller Name')),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('missed', 'Missed'), ('escalated', 'Escalated'), ('completed', 'Completed'), ('failed', 'Failed')], default='answered', max_length=20, verbose_name='Status')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20, verbose_name='Urgency')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True, verbose_name='Duration')),
                ('recording_url', models.URLField(blank=True, verbose_name='Recording URL')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('summary', models.TextField(blank=True, verbose_name='AI Summary')),
                ('customer_intent', models.CharField(blank=True, max_length=255, verbose_name='Customer Intent')),
                ('resolution', models.CharField(blank=True, max_length=100, verbose_name='Resolution')),
                ('handled_by', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='ai', max_length=20, verbose_name='Handled By')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Follow-up Required')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Follow-up Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='businesses.business')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Total Calls')),
                ('answered_calls', models.IntegerField(default=0, verbose_name='Answered Calls')),
                ('missed_calls', models.IntegerField(default=0, verbose_name='Missed Calls')),
                ('escalated_calls', models.IntegerField(default=0, verbose_name='Escalated Calls')),
                ('average_duration', models.IntegerField(blank=True, null=True, verbose_name='Average Duration (seconds)')),
                ('ai_resolved', models.IntegerField(default=0, verbose_name='AI Resolved')),
                ('human_resolved', models.IntegerField(default=0, verbose_name='Human Resolved')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_analytics', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Call Analytics',
                'verbose_name_plural': 'Call Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI Receptionist')], max_length=20, verbose_name='Speaker')),
                ('content', models.TextField(verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence Score')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='calls.call')),
            ],
            options={
                'verbose_name': 'Call Transcript',
                'verbose_name_plural': 'Call Transcripts',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['business', 'created_at'], name='calls_call_busines_2d3448_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='calls_call_status_03473e_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['urgency'], name='calls_call_urgency_078b96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callanalytics',
            unique_together={('business', 'date')},
        ),
    ]
