# Generated by Django 6.1.1 on 2026-09-30 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('channel', models.CharField(max_length=20, verbose_name='Channel')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_analytics', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Channel Analytics',
                'verbose_name_plural': 'Channel Analytics',
                'ordering': ['-date', '-count'],
                'unique_together': {('business', 'date', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Total Calls')),
                ('answered_calls', models.IntegerField(default=0, verbose_name='Answered Calls')),
                ('missed_calls', models.IntegerField(default=0, verbose_name='Missed Calls')),
                ('average_call_duration', models.IntegerField(blank=True, null=True, verbose_name='Average Call Duration (seconds)')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total Messages')),
                ('messages_replied', models.IntegerField(default=0, verbose_name='Messages Replied')),
                ('ai_resolved', models.IntegerField(default=0, verbose_name='AI Resolved')),
                ('human_resolved', models.IntegerField(default=0, verbose_name='Human Resolved')),
                ('escalated', models.IntegerField(default=0, verbose_name='Escalated')),
                ('new_contacts', models.IntegerField(default=0, verbose_name='New Contacts')),
                ('urgent_flags', models.IntegerField(default=0, verbose_name='Urgent Flags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
                'unique_together': {('business', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IntentAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('intent', models.CharField(max_length=255, verbose_name='Intent')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_analytics', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Intent Analytics',
                'verbose_name_plural': 'Intent Analytics',
                'ordering': ['-date', '-count'],
                'unique_together': {('business', 'date', 'intent')},
            },
        ),
    ]
