# Generated by Django 6.1.1 on 2026-09-30 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('website', 'Website Chat'), ('email', 'Email')], max_length=20, verbose_name='Channel')),
                ('summary', models.TextField(blank=True, verbose_name='AI Summary')),
                ('customer_intent', models.CharField(blank=True, max_length=255, verbose_name='Customer Intent')),
                ('resolution', models.CharField(choices=[('ai_resolved', 'AI Resolved'), ('escalated', 'Escalated'), ('human_resolved', 'Human Resolved'), ('pending', 'Pending'), ('abandoned', 'Abandoned')], default='pending', max_length=20, verbose_name='Resolution')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, verbose_name='Sentiment')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Follow-up Required')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Follow-up Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='businesses.business')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI Receptionist'), ('human', 'Human')], max_length=20, verbose_name='Sender')),
                ('content', models.TextField(verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UrgentFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='urgent', max_length=20, verbose_name='Level')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('keywords_detected', models.JSONField(blank=True, default=list, verbose_name='Keywords Detected')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_flags', to='conversations.conversation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Urgent Flag',
                'verbose_name_plural': 'Urgent Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business', 'started_at'], name='conversatio_busines_cfb354_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel'], name='conversatio_channel_aaf381_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['resolution'], name='conversatio_resolut_de7dea_idx'),
        ),
    ]
